//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bigidea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advices
    {
        public int Id { get; set; }
        public string PicUrl { get; set; }
        public string CoverStory { get; set; }
        public string Dinting { get; set; }
        public string Snakes { get; set; }
        public string Arbitrary { get; set; }
        public string Title { get; set; }
        public string Subhead { get; set; }
        public string Daoyan { get; set; }
    }
}
