//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bigidea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public Nullable<int> ArticleId { get; set; }
        public string Cont { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> CommentTime { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual User User { get; set; }
    }
}
