//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bigidea
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bigideaEntities : DbContext
    {
        public bigideaEntities()
            : base("name=bigideaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Advices> Advices { get; set; }
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<Collect> Collect { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Photos> Photos { get; set; }
        public virtual DbSet<Radios> Radios { get; set; }
        public virtual DbSet<ReArticle> ReArticle { get; set; }
        public virtual DbSet<View_Comment> View_Comment { get; set; }
        public virtual DbSet<View_Collect> View_Collect { get; set; }
        public virtual DbSet<RoleGive> RoleGive { get; set; }
        public virtual DbSet<View_User> View_User { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<View_Rec> View_Rec { get; set; }
    }
}
