//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bigidea
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReArticle
    {
        public int Id { get; set; }
        public int ArticleId { get; set; }
        public Nullable<int> PosId { get; set; }
        public Nullable<int> Weight { get; set; }
    }
}
